services:
  fastapi-backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - MODULE_NAME=app.main
      - VARIABLE_NAME=app

  react-frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - fastapi-backend